### ISSUE TITLE
Content is not initialized for "sfCacheTaggingToolkit"

### ISSUE THREAD

**Issue by greatwitenorth** [webvariants/policat#1]
During installation all the steps according to install.txt worked except the following:

```
$ php symfony doctrine:data-load
>> doctrine  Loading data fixtures from "/var/www/policat/data/fixtures"
>> doctrine  Loading data fixtures from "/var/www/policat/plugins/sfDoctrineGuardPlugin/data/fixtures"

  Content is not initialized for "sfCacheTaggingToolkit"
```

I'm not able to visit /dashboard either, just gives a 404 page.

**Comment by mcnilz** [comment]
data-load works with

    php symfony doctrine:data-load --application=frontend 

I added development with docker instructions on https://github.com/webvariants/policat/blob/develop/doc/docker-develop.md
